### ISSUE TITLE
Make specificitations more specific (add git commit hash to results rows)

### ISSUE THREAD

**Issue by pepyakin** [ashfurrow/xcode-hardware-performance#1]
### Fix Eidolon version

AFAIK, Eidolon is in active development. Specifying only project name you are implicitly saying that you are using master branch, which can be changed. 

So, I think it would be better to specify exact commit or tag to ensure tests repeatability.
### Simulator

I believe there may be some differences between starting simulator and app on iPad Pro and iPad 2.

**Comment by orta** [comment]
I was just coming to say it should be tied to a commit, let's tie it to this: https://github.com/artsy/eidolon/commit/71310c6af3df76ec20e061eb0b3b304d36eae5d9

**Comment by orta** [comment]
Also, re: the sim, we have a fleet of iPad Air 2s, so I'm willing to bet that's the sim being used, but making that specific is good too.

**Comment by ashfurrow** [comment]
Agreed that specifying iPad Air 2 is 👍 Not sure about the commit, since as the Xcode versions progress, people won't be able to run the code. Eidolon is stable-ish with no huge changes (well, one I guess) planned. I figured it was "close enough", but maybe you're right...

**Comment by pepyakin** [comment]
Oh, I just completely forgot about XCode thing, I'm not a iOS developer. Theoretically it could happen with iPad Air 2 as well — in some time in future it will be in same place where iPad(1) now is. 
I absolutely have no idea how you guys solve things like that.

**Comment by pepyakin** [comment]
Is there any point to measure simulator startup time at all?

**Comment by ashfurrow** [comment]
I went for an "absolute worst case", and sim startup varies across machines. 

Since the results are measured in minutes, I was willing to accept some imprecision. I think we either need to address that or clarify that it's somewhat of a moving target. Thoughts?

**Comment by amberstar** [comment]
I noticed that the initial simulator configuration matters too. If the simulator has to switch hardware from what it was last used as results are longer.

**Comment by ashfurrow** [comment]
Hmm. Good point. Hadn't considered the simulator switching hardware. Maybe specify that the simulator is iPad Air 2 and has been launched before in that config, but isn't running I guess?

**Comment by SFrost007** [comment]
I launched the iPad Air simulator on a clean install of Xcode (well, one on I hadn't run the simulator at all before) and had the additional start-up stage with a progress bar, which added ~1:20 over my subsequent tests. So it's certainly worth ensuring the simulator has booted cleanly before.

**Comment by ashfurrow** [comment]
Yeah, good point! I'm _really_ busy at the moment, would anyone be able to submit a pull request for this?

**Comment by ashfurrow** [comment]
Okay so following up I think a good approach would be to add a reference (git commit sha?) to each row. It won't be useful for most developers but if someone wants to dive into the details, they'll have the necessary information.

Going to rename this issue accordingly. Thanks again everyone.
