### ISSUE TITLE
Table is hard to read

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/xcode-hardware-performance#17]
It's way too narrow when rendered on the main repo page. We should remove things that are redundant or too verbose:
- "-inch" can be the `"`.
- We don't need to specify "Intel" anymore :stuck_out_tongue: 
- Retina can be symbolized with the `r` prefix. 

So this:

> MacBook (Retina, 12-inch, Early 2015) | 1.1 GHz Intel Core M

Can become:

> 12" rMacBook Early 2015 | 1.1 GHz Core M

And we can hopefully make things more legible.

**Comment by pepyakin** [comment]
Also, they are sorted by time when they were added. 
Will it make more sense if they were sorted by Fresh Build Time or Incremental Build Time?

**Comment by ashfurrow** [comment]
Maybe instead sort by hardware release date? So they're easier to find.

**Comment by pepyakin** [comment]
But how do you sort devices with one release date? What is "greater": iMac or MacBook, iMac or Mac Pro, or even MacBook Pro "13 or MacBook Pro "15?

**Comment by ashfurrow** [comment]
As long as it's consistent it doesn't matter to me

**Comment by pepyakin** [comment]
Order them like on apple web site?
<img width="544" alt="screenshot 2015-11-14 01 28 27" src="https://cloud.githubusercontent.com/assets/2205845/11159260/0f0f2ab8-8a6f-11e5-8402-b6575404386c.png">
Another option is to order by size.

**Comment by ashfurrow** [comment]
Good idea!

**Comment by ashfurrow** [comment]
Interesting: https://github.com/blog/2085-a-new-look-for-repositories

**Comment by orta** [comment]
Add a newline after the type of the computer, should fix most of your scanning problems
