### ISSUE TITLE
Geekbench Correlations

### ISSUE THREAD

**Issue by ashfurrow** [ashfurrow/xcode-hardware-performance#19]
Geekbench has [know relative measurements of different Macs](https://browser.primatelabs.com/mac-benchmarks). What could be _really_ cool is to chart these measurements against _our_ measurements to find a correlation between the two. Then we can predict build times for any given Mac based on its Geekbench score. 

I'll see if I can get around to this on the weekend.

**Comment by brentleyjones** [comment]
That would be awesome!

**Comment by Buju77** [comment]
any news on this? :)

**Comment by Jake3231** [comment]
@ashfurrow Do you still plan to add this to the repository?

**Comment by ashfurrow** [comment]
@Jake3231 hey, thanks for the poke. I probably won't get to this so if someone else wants to do it, I'd recommend their own repo 👍 We can link to it from here. I just don't think that include Geekbench results sends the right message for what this repo is, which is very unscientific. I don't want to become an authority on Mac hardware performance because it's outside my general wheelhouse and I'd probably get it wrong 😅
