### ISSUE TITLE
Including Xcode Version in the table may be better

### ISSUE THREAD

**Issue by ergunkocak** [ashfurrow/xcode-hardware-performance#37]
Including Xcode Version in the table may be better ;)

**Comment by ashfurrow** [comment]
Probably ¯\\_(ツ)_/¯ Bit late now, and the project has languished a bit. It was really meant to be an unscientific, relative comparison. Does that make sense? I'm certainly not opposed to adding a Xcode version column though!

**Comment by ashfurrow** [comment]
We've actually separated these out into two tables now, thanks for the idea 👍

**Comment by ergunkocak** [comment]
Shall we also seperate it according to Swift version ? :)

**Comment by ashfurrow** [comment]
Since Xcode 9 uses the same compile for Swift 3 and 4, I think we should be okay 🌟

**Comment by ergunkocak** [comment]
My experience with Xcode9 is somewhat different :( My project was compiling in xcode8 in 2 minutes but after a setting a build switch i managed to reduce it to 1 minute. But with xcode9 and swift 4 same project started to compile in 3 minutes
