### ISSUE TITLE
Add test date/app version 

### ISSUE THREAD

**Issue by dmcyk** [ashfurrow/xcode-hardware-performance#39]
Taking into account that the testing project is under active development I'd imagine its complexity is increasing - maybe new dependencies are being added etc., therefore I think it would be good to add date of tests or version of the project under which the performance test had been done.

**Alternative consideration**: or maybe instead, you could embed buildable version of the project in this repo and use that specific commit for tests so that everyone is testing against same configuration. 

Thanks for your work!

**Comment by ashfurrow** [comment]
I agree, we should at least add a caveat to the Readme that the current results are all for Xcode 8 and Swift 3.x. Maybe even create a new section for Xcode 9. Thoughts? I'm flexible – maybe just adding a date or Xcode version column makes sense.

**Comment by dmcyk** [comment]
I guess it'd be good to have both, date of a test as a reference to the testing project state and Xcode version itself, maybe someone'd have better idea though. 

Speaking of Xcode 9,  I guess it'd be good to specify which build system should be used. Haven't compared myself but I've heard the new one is significantly faster, especially with incremental builds.

**Comment by ashfurrow** [comment]
Okay, I've added a note to the readme. Once Xcode 9 comes out, we can be a little more rigorous. Let me know if you have any more ideas!
