### ISSUE TITLE
Xcode Build System

### ISSUE THREAD

**Issue by JagCesar** [ashfurrow/xcode-hardware-performance#54]
Hey,

Thanks for throwing this together. When you compiled, did you try out the [New Build System](https://jamesdempsey.net/2017/06/13/new-xcode-build-system-and-buildsettingextractor/), and if so did you see any speed performances?

I'm hoping the new build system is better when more cores are available.

Stay awesome!

**Comment by JagCesar** [comment]
Bah. Just noticed the `New Build System` column in the Readme. I'll show myself out… 🤦‍♂️

**Comment by ashfurrow** [comment]
No worries! That @ashfurrow-peril bot bug happened, so now I've got debug info :)
