### ISSUE TITLE
can we add new mac mini 2018

### ISSUE THREAD

**Issue by scorlingonzalez** [ashfurrow/xcode-hardware-performance#82]
hey guys can we add all new mac mini please

**Comment by beeradmoore** [comment]
I have the top spec i7 coming tomorrow, but I’ve never successfully ran these tests on my last machine. Will give it a go tomorrow after xcode is installed and post if I have issues.

I’m a Xamarin developer so I don’t usually play around with Xcode :p

**Comment by scorlingonzalez** [comment]
that is super dope, am looking at the i5 model but i really wanted to see Xcode performance on it relative to these other machines here. am really trying save me those 2 to 3 hundred dollars by not getting the i7.

**Comment by beeradmoore** [comment]
Added with #83, going to try add my mid-2014 MacBook Pro building but its having fastlane issues.

I also I don't fully trust peoples times are with simulator closed and waiting for the app to become visible on the simulator.

**Comment by scorlingonzalez** [comment]
thank you, i really appreciate what you have done here. is there a chance that you will do the new i5 Mac mini any time soon. this new mac mini is looking very promising am just curious to see what the i5 numbers would be like before i pull the trigger next week

**Comment by beeradmoore** [comment]
@scorlingonzalez can you close this issue now :)
