### ISSUE TITLE
Duplicate entry

### ISSUE THREAD

**Issue by tshakalekholoane** [ashfurrow/xcode-hardware-performance#88]
There appears to be a duplicate entry in the Readme.md for the Mac Mini, Late 2018, 512GB SSD under the X Code 10 table.

**Comment by ashfurrow** [comment]
You're right! Would you like to submit a PR to remove the duplicate?

**Comment by tshakalekholoane** [comment]
Yes 😊 just did.

**Comment by ashfurrow** [comment]
Thanks! Closed by #89.
