### ISSUE TITLE
Cost more time with No DerivedData cache

### ISSUE THREAD

**Issue by tanpengsccd** [ashfurrow/xcode-hardware-performance#95]
if i do 
```
rm -rf ~/Library/Developer/Xcode/DerivedData/
```
it will cost more time.
so I think should  cmd+shift+k ,and remove  **DerivedData** will more accurate.

**Comment by ashfurrow** [comment]
Hi, thanks for opening the issue. I don't agree that deleting that directory would be more accurate – most developers clear their build with Xcode, and this repo's goal is providing real-world results. While this repo isn't meant to give scientific-levels of accuracy, the testing methodology should still follow the most common developer workflow, which is Xcode. 

Thanks again, and let me know what I can clarify!
